### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by justyns** [justyns/silverbullet-ai#16]
Before the readme gets too big..

**Comment by zefhemel** [comment]
Somewhere else you suggested using silverbullet-pub for this, I've now added a sample GH actions workflow to the repo that you can use. Only annoying thing is that GH pages by default publishes to a sub-directory unless you configure a custom domain, which breaks (it assume it's deployed to the root). In case you want to set this up though, I'd be happy to point e.g. `ai.silverbullet.md` to it, just let me know. I'm publishing https://pub2.silverbullet.md using GH pages and GH actions from that repo now, works fine.

**Comment by justyns** [comment]
Thanks for the offer, that'd be great!  

I was experimenting with cloudflare pages a little bit, mostly only because you can have different subdomains for each branch/commit if you want.   I'm leaning towards keeping it simpler and sticking to gh pages though.

**Comment by zefhemel** [comment]
I’ve just CNAMEd `ai.silverbullet.md` to `justyns.github.io` which is supposed to work. You can configure `ai.silverbullet.md` as a custom domain for GH pages now, that should work (once DNS propagates).

**Comment by justyns** [comment]
Thanks @zefhemel , that worked without any issues.  I had to publish something to gh pages first, but https://ai.silverbullet.md/ is loading now.    Now I just need to find some time to work on it this week 😅

**Comment by creer** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
d1m0nh, @myself659, @annsemm, @lidelin, @shod4n, @beldar, @robkuo, @acriptis, @gglive, @rg7822, @CheeseDeployer, @LIWEIDENG0830, @setkeh, @dryruner, @davidchen3700, @fc500110, @cheekybastard, @pulsecat, @AaronDeb, @njvitto, @maxme, @aymericbeaumet, @negativefactorial, @leventozen, @iamjcares, @newbie-coin, @cwaring, @walne, @mb1689, @seandewar, @sbutalia, @dunphyben, @R3dFruitRollUp, @leozhanng, @DrOctogon, @BlueDayMonkey, @jakarmy, @herrSimple, @fakegit, @s-brez, @sandro, @xyang532, @sachalevy, @jmxt3, @VaughnGH, @zfs002, @EricGrill, @hangocanhha, @discountry, @tzarskyz
