### ISSUE TITLE
Gemini API Support

### ISSUE THREAD

**Issue by justyns** [justyns/silverbullet-ai#3]
Relevant doc:  https://ai.google.dev/tutorials/rest_quickstart

Note that this would depend on first adding support for configuring multiple models and having some sort of generic interface for different LLM backend api types.

**Comment by zefhemel** [comment]
Why oh why don't they just implement the OpenAI conversation API...

**Comment by justyns** [comment]
This seems to work decently well.  If anyone has issues, please let me know!
